import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { labelFor } from '../audit/fingerprints.js';
import { dataDir } from '../lib/env.js';
import { log } from '../lib/log.js';
import { primaryContact } from '../lib/store.js';
import { nowIso } from '../lib/util.js';

// When a prospect says yes, the build happens in Claude Code. This writes the
// brief to start that session with: everything the pipeline learned about the
// business, what to fix, and the quality bar, in one markdown file.

const PAGES = {
  websites: ['Home', 'One page per core service', 'Service area (only places they really serve)', 'About', 'Reviews', 'Contact / request a quote', 'Privacy policy'],
  automation: ['Workflow map: every way leads and requests arrive today, and where they wait', 'Automations to build, in order of hours saved', 'Integrations and accounts needed', 'Escalation rules: when a person takes over'],
  apps: ['Core job of the app in one sentence', 'Screens for the first version', 'Accounts, payments, notifications', 'Integrations (booking, POS, CRM)', 'App store listing and privacy forms'],
};

export function buildBrief(company, config) {
  const service = company.primaryService ?? company.serviceHint ?? 'websites';
  const brand = company.brand ?? company.audit?.brand ?? {};
  const s = company.audit?.signals;
  const contact = primaryContact(company);
  const findings = (company.findings ?? []).filter((f) => f.weight > 0 && f.service === service);
  const tech = s ? [...s.tech.builder, ...s.tech.cms, ...s.tech.framework, ...s.booking, ...s.chat, ...s.crm, ...s.analytics].map(labelFor) : [];
  const lines = [
    `# Build brief: ${company.name}`,
    '',
    `${config.services[service].label} project for ${company.name}${company.domain ? ` (${company.domain})` : ''}. Generated by \`mb brief\` on ${nowIso().slice(0, 10)} from the lead record; confirm anything marked "check".`,
    '',
    '## The business',
    '',
    `- Name: ${company.name}`,
    company.industry && `- Industry: ${company.industry}`,
    (company.city || brand.address?.city) && `- Location: ${[company.city ?? brand.address?.city, company.state ?? brand.address?.region].filter(Boolean).join(', ')}`,
    brand.address?.full && `- Address: ${brand.address.full} (check)`,
    company.phone && `- Phone: ${company.phone}`,
    company.rating && `- Google rating: ${company.rating} from ${company.reviewCount} reviews${company.mapsUrl ? ` (${company.mapsUrl})` : ''}`,
    contact && `- Contact: ${[contact.firstName, contact.lastName].filter(Boolean).join(' ') || 'unknown name'}${contact.title ? `, ${contact.title}` : ''}${contact.email ? ` <${contact.email}>` : ''}`,
    company.website && `- Current site: ${company.website}`,
    tech.length && `- Current tools: ${tech.join(', ')}`,
    '',
    '## Brand',
    '',
    brand.logo ? `- Logo: ${brand.logo} (get the original file from the client)` : '- Logo: none found; ask the client',
    brand.colors?.length ? `- Colors seen on their site: ${brand.colors.join(', ')}` : '- Colors: none found; ask or propose',
    brand.tagline && `- Their current description: "${brand.tagline}"`,
    brand.services?.length && `- Services they list: ${brand.services.join('; ')}`,
    company.demo?.url && `- Concept homepage we already showed them: ${company.demo.url}`,
    '',
    '## What to fix (from our audit)',
    '',
    ...(findings.length ? findings.map((f) => `- **${f.title}**: ${f.point}`) : ['- Nothing flagged; focus on the goals below.']),
    '',
    `## Scope to confirm`,
    '',
    ...PAGES[service].map((p) => `- [ ] ${p}`),
    '',
    '## Quality bar',
    '',
    ...(service === 'websites'
      ? [
          '- Mobile-first; tap-to-call and the main CTA always within reach on phones',
          '- Google PageSpeed (mobile) 90+; images resized and in modern formats; no render-blocking third parties',
          '- Unique titles and meta descriptions, one H1 per page, LocalBusiness schema, sitemap.xml, robots.txt',
          '- 301 redirects from every old URL that had traffic',
          '- WCAG AA contrast, alt text, keyboard navigation',
          '- Forms deliver to the client and send an instant confirmation; spam protection on',
          '- Deployed to Cloudflare; client owns the domain and gets the code',
        ]
      : service === 'automation'
        ? [
            '- Every automated message is reviewed by the client before launch',
            '- Clear human hand-off for anything outside the script',
            '- Disclose automation to customers; follow texting rules (A2P 10DLC) and recording-consent laws',
            '- Vendors handling health data sign a BAA',
            '- Logging and a weekly report on volume, outcomes, and escalations',
          ]
        : [
            '- One core job done extremely well in v1',
            '- Privacy policy, data-safety and privacy-label answers ready before submission',
            '- Crash reporting and basic analytics from day one',
            '- Store listing copy and screenshots',
          ]),
    '',
    '## Voice',
    '',
    'Plain-spoken and specific, in the business’s own words where possible. Reuse facts from their current site; never invent claims (licenses, years, guarantees, reviews).',
    '',
  ];
  return lines.filter((line) => line !== false && line !== null && line !== undefined && line !== 0).join('\n');
}

export async function brief({ config, store }, args) {
  const [id] = args.positionals;
  const company = id && (await store.get(id));
  if (!company) throw new Error(`Usage: mb brief <id>   (no lead "${id ?? ''}")`);
  const dir = path.join(dataDir(), 'briefs');
  await mkdir(dir, { recursive: true });
  const file = args.values.out ?? path.join(dir, `${company.id}.md`);
  await writeFile(file, buildBrief(company, config));
  log.ok(`Brief: ${path.relative(process.cwd(), file)}`);
  log.info('Start the build in Claude Code with: "Build this client\'s site from the brief at <path>, in a new repo, deploying to Cloudflare."');
}
